#if !canImport(ObjectiveC)
import XCTest

extension MockTelloFlightTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockTelloFlightTests = [
        ("testChainFailoverFail", testChainFailoverFail),
        ("testChainFailoverSucceed", testChainFailoverSucceed),
        ("testFlightChain", testFlightChain),
        ("testFlightChainFail", testFlightChainFail),
        ("testImplicitTimerInvalidate", testImplicitTimerInvalidate),
        ("testKeepAlive", testKeepAlive),
        ("testLandAndBlock", testLandAndBlock),
        ("testLandAndCommand", testLandAndCommand),
        ("testLandAndShutdown", testLandAndShutdown),
        ("testMovement", testMovement),
        ("testShutdown", testShutdown),
        ("testTakeoff", testTakeoff),
        ("testTakeoffAndBlock", testTakeoffAndBlock),
        ("testValidateCombined", testValidateCombined),
        ("testValidateDistance", testValidateDistance),
        ("testValidateNilEmpty", testValidateNilEmpty),
        ("testValidateSpeed", testValidateSpeed),
    ]
}

extension MockTelloHandlerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockTelloHandlerTests = [
        ("testFailureHandler", testFailureHandler),
        ("testMockAsyncCommand", testMockAsyncCommand),
        ("testMockInOneTello", testMockInOneTello),
        ("testMockNestAsyncSync", testMockNestAsyncSync),
        ("testMockNestAsyncSyncAsync", testMockNestAsyncSyncAsync),
        ("testMockNestTripleAsync", testMockNestTripleAsync),
        ("testMockNilHandler", testMockNilHandler),
        ("testMockSyncCommand", testMockSyncCommand),
    ]
}

extension MockTelloStateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockTelloStateTests = [
        ("testAcceleration", testAcceleration),
        ("testAngAcc", testAngAcc),
        ("testAtt", testAtt),
        ("testAttitude", testAttitude),
        ("testBaro", testBaro),
        ("testBattery", testBattery),
        ("testDeinit", testDeinit),
        ("testEDU", testEDU),
        ("testGetSpeed", testGetSpeed),
        ("testHeight", testHeight),
        ("testMaxTemperature", testMaxTemperature),
        ("testMinTemperature", testMinTemperature),
        ("testSetSpeed", testSetSpeed),
        ("testSNSDK", testSNSDK),
        ("testTemperature", testTemperature),
        ("testTime", testTime),
        ("testTof", testTof),
        ("testWifi", testWifi),
    ]
}

extension MockTelloVideoTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MockTelloVideoTests = [
        ("testStreamDelegate", testStreamDelegate),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MockTelloFlightTests.__allTests__MockTelloFlightTests),
        testCase(MockTelloHandlerTests.__allTests__MockTelloHandlerTests),
        testCase(MockTelloStateTests.__allTests__MockTelloStateTests),
        testCase(MockTelloVideoTests.__allTests__MockTelloVideoTests),
    ]
}
#endif
